### ISSUE TITLE
Time Labels Color(s)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/labels#10] opened 2016-10-07 00:23 UTC
At _present_ our Time (_estimation_) Labels are different colors: https://github.com/dwyl/labels/labels
![time-labels-colors](https://cloud.githubusercontent.com/assets/194400/19175214/c1c3d4aa-8c2c-11e6-90c2-2fdf040f7232.png)

This makes it ~~hard~~ _difficult_ to _scan_ through a list of issues e.g: https://github.com/emfoundation/ce100-app/milestone/3 and see which ones have a time estimate label applied.

@iteles please _remind_ us why the labels have different colors... was it to signify a "scale" e.g. darker pink is more time...?

> for the record I think they should all be the same color so its _easy_ to glance at the list of issues and see Time Estimate. or if we are going for a "range", we should _first_ agree on what "_levels_" of time estimation we are going to do and then _could_ go on http://www.color-hex.com/color/f7c6c7 and select different (_but still v. similar and thus "scannable"_) tones of the same color for the "_spectrum of effort_"...

**Comment by iteles** [comment] 2016-10-07 00:49
The thinking behind having two shades of pink for the time labels was so that tasks under half a day were easily identifiable should the person wanting to contribute have a smaller time block on their hands. 

The shades may be a little too disparate to function correctly however. What do others using these think? @simonlab @danwhy @naazy @conorc1000 @jmurphyweb @mk4111

**Comment by nelsonic** [comment] 2016-10-07 01:38
@iteles stories/issues/tasks should _only_ be _estimated_ when they are going to be included in the milestone (_or started immediately_) _preferably_ by the people/person who is going to do the _work_. 

If people _never_ start working on another issue/task _before_ estimating it again, I _really_ don't mind what colors are used for the labels. The _reason_ I opened this issue was because I see milestones ("sprints") with quite a _few_ issues which are unestimated ... 

![image](https://cloud.githubusercontent.com/assets/194400/19176333/9b887714-8c36-11e6-9450-e236ed5fefa7.png)

**Comment by iteles** [comment] 2016-10-18 21:15
This has been changed in this repo. Could you please review and close this issue @nelsonic ?

It should be noted that as a person who has to answer a *lot* of client questions on timelines, I find it incredibly useful to have a quick understanding of which tasks are 'quick' tasks (under and hour) and which ones extend into half a day plus.

I was also in the situation today where when sprint planning I was able to quickly scan the backlog and pick out a couple of small but high value features quickly to add more value to the sprint and also have a good idea at a glance of how full a sprint really is (lots of dark pinks vs lots of light pinks).

I'm happy to be outvoted on this one as it seems people find it more unhelpful than helpful, but wanted to document the above for future reference once the issue is closed.

**Comment by nelsonic** [comment] 2016-10-21 21:41
@iteles I _prefer_ the lighter pink.
![dark-pink-with-black-text](https://cloud.githubusercontent.com/assets/194400/19612594/6f95a4ba-97df-11e6-934c-71ef28639964.png)

Dark pink with black text is not great. 😕

**Comment by iteles** [comment] 2016-10-21 22:01
Done.

<img width="141" alt="screen shot 2016-10-21 at 23 00 52" src="https://cloud.githubusercontent.com/assets/4185328/19613090/4a296e0c-97e2-11e6-8dcb-59c4df54a298.png">

**Comment by nelsonic** [comment] 2016-10-22 15:33
I should have phrased that better... but thanks for changing them. 👍

**Closed** 2017-02-02 23:02 UTC
Labels: discuss
